const dummyData = [
  {
    id: 1,
    name: "John Doe",
    status: "Outgoing",
    date: "Today, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    status: "Incoming",
    date: "Yesterday, 11:30 PM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Alice Johnson",
    status: "Incoming",
    date: "Wednesday, 12:30 PM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    name: "Bob Williams",
    status: "Outgoing",
    date: "Last Monday, 08:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    name: "James Brown",
    status: "Missed",
    date: "Last Week, 09:30 PM",
    isMissed: true,
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Sarah Taylor",
    status: "Outgoing",
    date: "This Month, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    name: "Paul Miller",
    status: "Incoming",
    date: "Yesterday, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Diana Brown",
    status: "Incoming",
    date: "Last Sunday, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Chris Johnson",
    status: "Missed",
    date: "Last Year, 10:30 AM",
    isMissed: true,
    photo: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "Sarah Taylor",
    status: "Outgoing",
    date: "Today, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 11,
    name: "Paul Miller",
    status: "Incoming",
    date: "Yesterday, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Diana Brown",
    status: "Incoming",
    date: "Yesterday, 10:30 AM",
    isMissed: false,
    photo: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 13,
    name: "Chris Johnson",
    status: "Missed",
    date: "Yesterday,4:30 AM",
    isMissed: true,
    photo: "https://randomuser.me/api/portraits/women/7.jpg",
  },
];

export default dummyData;
